In [19]:
#EX2-version-1
from fractions import Fraction
import numpy as np
np.set_printoptions(formatter={'all':lambda x: str(Fraction(x).limit_denominator())})

In [20]:
array1 = np.arange(1,10,1).reshape(3,3)
array2 = np.empty((3,3))

In [23]:
for i in range(array1.shape[0]):
    for j in range(array1.shape[1]):
        temp =sum(list(map(lambda x:1.0/x,array1[i])))
        array2[i][j] = array1[i][j]*temp   

In [24]:
array2

array([[11/6, 11/3, 11/2],
       [37/15, 37/12, 37/10],
       [191/72, 191/63, 191/56]])

In [99]:
#EX2-version-2
import numpy as np
array1=np.arange(1,10).reshape(3,3)
temp = 1/array1
array2=np.full((3,3),temp.sum(1)).T*array1

In [100]:
array2

array([[11/6, 11/3, 11/2],
       [37/15, 37/12, 37/10],
       [191/72, 191/63, 191/56]])

In [109]:
#EX2-version-3
A = np.arange(1,10).reshape(3,-1)
A*((1/A).sum(1).reshape(-1,1))

array([[11/6, 11/3, 11/2],
       [37/15, 37/12, 37/10],
       [191/72, 191/63, 191/56]])