In [1]:
import numpy as np

In [69]:
a = np.array([1,2,5,6,7])
a

array([1, 2, 5, 6, 7])

In [72]:
np.diff(a)

array([1, 3, 1, 1])

In [76]:
np.r_[1,np.diff(a)!=1,1]

array([1, 0, 1, 0, 0, 1], dtype=int32)

In [77]:
np.nonzero(np.r_[1,np.diff(a)!=1,1])

(array([0, 2, 5], dtype=int64),)

In [78]:
np.diff(np.nonzero(np.r_[1,np.diff(a)!=1,1]))

array([[2, 3]], dtype=int64)

In [75]:
np.diff(np.nonzero(np.r_[1,np.diff(a)!=1,1])).max()

3