In [1]:
import numpy as np

In [2]:
np.random.seed(0)
A = np.random.randint(10,20,(8,5))
A

array([[15, 10, 13, 13, 17],
       [19, 13, 15, 12, 14],
       [17, 16, 18, 18, 11],
       [16, 17, 17, 18, 11],
       [15, 19, 18, 19, 14],
       [13, 10, 13, 15, 10],
       [12, 13, 18, 11, 13],
       [13, 13, 17, 10, 11]])

In [29]:
#EX3-version-1
c = np.ones((8,5))
B = (np.full((8,5),A.sum(0)))*((A.sum(1)*c.T).T)/A.sum()
result = (((A-B)**2)/B).sum()
result

11.842696601945802

In [7]:
#5列
A.sum(0)

array([120, 111, 129, 116, 101])

In [8]:
#8行
A.sum(1)

array([68, 73, 80, 79, 85, 61, 67, 64])

In [37]:
#EX3-version-2
B = A.sum(0)*(A.sum(1).reshape(-1,1))/A.sum()
(((A-B)**2)/B).sum()

11.842696601945802